In [1]:
import os
import pandas as pd
os.chdir('C:/Users/basleal/Desktop/tutorial/kaim-week-6')
print(os.getcwd())

C:\Users\basleal\Desktop\tutorial\kaim-week-6

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
path = 'C:/Users/basleal/Desktop/tutorial/kaim-week-6/data/data.csv'

In [4]:
data=pd.read_csv(path)

In [5]:
data.columns

Index(['TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId',
       'CurrencyCode', 'CountryCode', 'ProviderId', 'ProductId',
       'ProductCategory', 'ChannelId', 'Amount', 'Value',
       'TransactionStartTime', 'PricingStrategy', 'FraudResult'],
      dtype='object')

In [6]:
print(data.nunique())

TransactionId           95662
BatchId                 94809
AccountId                3633
SubscriptionId           3627
CustomerId               3742
CurrencyCode                1
CountryCode                 1
ProviderId                  6
ProductId                  23
ProductCategory             9
ChannelId                   4
Amount                   1676
Value                    1517
TransactionStartTime    94556
PricingStrategy             4
FraudResult                 2
dtype: int64

In [7]:
from scripts.feature_eng import num_aggregate
agg_num=num_aggregate(data)
agg_num

KeyError: "Columns not found: 'TransactionYear'"

In [33]:
from scripts.feature_eng import cat_aggregate
agg_cat=cat_aggregate(data)
agg_cat

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,ProviderId,ProductId,ProductCategory,ChannelId
CustomerId,,,,,,,,,,
CustomerId_1,TransactionId_51888,BatchId_22790,AccountId_1074,SubscriptionId_4836,CustomerId_1,UGX,ProviderId_4,ProductId_10,airtime,ChannelId_2
CustomerId_10,TransactionId_24254,BatchId_4854,AccountId_1074,SubscriptionId_4836,CustomerId_10,UGX,ProviderId_4,ProductId_3,airtime,ChannelId_2
CustomerId_1001,TransactionId_11879,BatchId_118083,AccountId_661,SubscriptionId_4753,CustomerId_1001,UGX,ProviderId_4,ProductId_10,financial_services,ChannelId_3
CustomerId_1002,TransactionId_102164,BatchId_10941,AccountId_4841,SubscriptionId_3829,CustomerId_1002,UGX,ProviderId_4,ProductId_6,financial_services,ChannelId_2
CustomerId_1003,TransactionId_124850,BatchId_121394,AccountId_663,SubscriptionId_3559,CustomerId_1003,UGX,ProviderId_6,ProductId_10,airtime,ChannelId_3
...,...,...,...,...,...,...,...,...,...,...
CustomerId_992,TransactionId_110861,BatchId_115940,AccountId_652,SubscriptionId_2615,CustomerId_992,UGX,ProviderId_6,ProductId_10,airtime,ChannelId_3
CustomerId_993,TransactionId_107496,BatchId_102009,AccountId_653,SubscriptionId_4236,CustomerId_993,UGX,ProviderId_4,ProductId_10,financial_services,ChannelId_3
CustomerId_994,TransactionId_100294,BatchId_101233,AccountId_654,SubscriptionId_2266,CustomerId_994,UGX,ProviderId_6,ProductId_6,financial_services,ChannelId_3
CustomerId_996,TransactionId_10585,BatchId_28262,AccountId_656,SubscriptionId_3753,CustomerId_996,UGX,ProviderId_1,ProductId_15,financial_services,ChannelId_3
CustomerId_998,TransactionId_11160,BatchId_102067,AccountId_658,SubscriptionId_3215,CustomerId_998,UGX,ProviderId_4,ProductId_6,airtime,ChannelId_3

In [8]:
from scripts.feature_eng import extract_date
data= extract_date(data)
data.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,TransactionHour,TransactionDay,TransactionMonth,TransactionYear
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15 02:18:49+00:00,2,0,2,15,11,2018
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15 02:19:08+00:00,2,0,2,15,11,2018
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15 02:44:21+00:00,2,0,2,15,11,2018
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15 03:32:55+00:00,2,0,3,15,11,2018
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15 03:34:21+00:00,2,0,3,15,11,2018

In [9]:
'CurrencyCode', 'CountryCode', 'ProductCategory', 'ChannelId'

data.nunique()

TransactionId           95662
BatchId                 94809
AccountId                3633
SubscriptionId           3627
CustomerId               3742
CurrencyCode                1
CountryCode                 1
ProviderId                  6
ProductId                  23
ProductCategory             9
ChannelId                   4
Amount                   1676
Value                    1517
TransactionStartTime    94556
PricingStrategy             4
FraudResult                 2
TransactionHour            24
TransactionDay             31
TransactionMonth            4
TransactionYear             2
dtype: int64

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95662 entries, 0 to 95661
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TransactionId         95662 non-null  object
 1   BatchId               95662 non-null  object
 2   AccountId             95662 non-null  object
 3   SubscriptionId        95662 non-null  object
 4   CustomerId            95662 non-null  object
 5   CurrencyCode          95662 non-null  object
 6   CountryCode           95662 non-null  int64
 7   ProviderId            95662 non-null  object
 8   ProductId             95662 non-null  object
 9   ProductCategory       95662 non-null  object
 10  ChannelId             95662 non-null  object
 11  Amount                95662 non-null  float64
 12  Value                 95662 non-null  int64
 13  TransactionStartTime  95662 non-null  datetime64[ns, UTC]
 14  PricingStrategy       95662 non-null  int64
 15  FraudResult           95662 non-null  int64
 16  TransactionHour       95662 non-null  int32
 17  TransactionDay        95662 non-null  int32
 18  TransactionMonth      95662 non-null  int32
 19  TransactionYear       95662 non-null  int32
dtypes: datetime64[ns, UTC](1), float64(1), int32(4), int64(4), object(10)
memory usage: 13.1+ MB

In [20]:
from scripts.feature_eng import onehot_encoding
data=onehot_encoding(data)
data

KeyError: "None of [Index(['CurrencyCode', 'CountryCode', 'ProductCategory', 'ChannelId'], dtype='object')] are in the [columns]"

In [21]:
data.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,ProviderId,ProductId,Amount,Value,TransactionStartTime,...,ProductCategory_financial_services,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,5,ProductId_10,1000.0,1000,2018-11-15 02:18:49+00:00,...,0,0,0,0,0,0,0,0,1,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,3,ProductId_6,-20.0,20,2018-11-15 02:19:08+00:00,...,1,0,0,0,0,0,0,1,0,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,5,ProductId_1,500.0,500,2018-11-15 02:44:21+00:00,...,0,0,0,0,0,0,0,0,1,0
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,0,ProductId_21,20000.0,21800,2018-11-15 03:32:55+00:00,...,0,0,0,0,0,0,1,0,1,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,3,ProductId_6,-644.0,644,2018-11-15 03:34:21+00:00,...,1,0,0,0,0,0,0,1,0,0

In [25]:
from scripts.feature_eng import scaler
data=scaler(data)
data.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,ProviderId,ProductId,Amount,Value,TransactionStartTime,...,ProductCategory_financial_services,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,5,ProductId_10,0.092004,0.000101,2018-11-15 02:18:49+00:00,...,0,0,0,0,0,0,0,0,1,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,3,ProductId_6,0.091910,0.000002,2018-11-15 02:19:08+00:00,...,1,0,0,0,0,0,0,1,0,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,5,ProductId_1,0.091958,0.000050,2018-11-15 02:44:21+00:00,...,0,0,0,0,0,0,0,0,1,0
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,0,ProductId_21,0.093750,0.002206,2018-11-15 03:32:55+00:00,...,0,0,0,0,0,0,1,0,1,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,3,ProductId_6,0.091853,0.000065,2018-11-15 03:34:21+00:00,...,1,0,0,0,0,0,0,1,0,0

In [26]:
# saved our newly transformed data
data.to_csv('data_ready_train.csv')